### ISSUE TITLE
GPU integration checklist

### ISSUE THREAD

**Issue by ptiede** [EHTJulia/VLBISkyModels.jl#38]
- [ ]  Add GPU caches for `NFFT`, `DFT` and `FFT`
- [ ]  `_apply_scaling!` has a for loop over data on the cpu
- [ ]  `_frule_vis` is not GPU friendly

**Comment by ptiede** [comment]
Will be fixed by #120 (mostly)
