### ISSUE TITLE
4D image support checklist

### ISSUE THREAD

**Issue by ptiede** [EHTJulia/VLBISkyModels.jl#53]
These are the things that need to be fixed to support multifrequency imaging.

- [x] `ContinuousImage` really only works for spatial images. The summation for `intensity_point` is incorrect for Ti and Fr
- [x] `FourierDualDomain` DFT, FFT, and NFFT all have to be ported to loop over non-spatial dimensions
- [x]  `uvgrid`, `padded_uvgrid` and so forth only work for `SpatialIntensityMaps` 
- [x] `InterpolatedModel` only works with spatial intensitymaps
- [x] Implement the clever caching for all the numerical FFT's (~~NFFT and DFT~~ (done in #56) should be easiest)
- [x] ~~Maybe rework the type hierarchy to differentiate between purely spatial and more complicated models (traits?)~~
- [x] PoincareSphere2Map needs to be updated to work with spatial and temporal models
- [x] Make combinators (add and convolved model) work correctly with 4D images

**This will be continually updated**

**Comment by ptiede** [comment]
@rohandahale

**Comment by ptiede** [comment]
The rest of these will be handled by #73

**Comment by ptiede** [comment]
ContinuousImage will be handled by Erandi's work

**Comment by ptiede** [comment]
PoincareSphere2Map and other polarized converters will work out of the box if the dimensions match so that is fine. Now getting a proper multifrequency and time dependent polarized model is not so we will punt on that.
